### ISSUE TITLE
VegaLite selection in Jupyter

### ISSUE THREAD

**Issue by oheil** [fredo-dedup/VegaLite.jl#105]
Playing around with VegaLite.jl in an jupyter/IJulia notebook I tried to translate an interactive example fron the VegaLite web page:
[Interactive Average](https://vega.github.io/vega-lite/examples/selection_layer_bar_month.html)
The following code reproduces the plot without the interaction:
```
using VegaLite, DataFrames
data = DataFrame(
    date=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    precipitation=[3.8,3.7,4.9,3.1,1.6,1.1,0.3,1.2,1.9,4.1,5.2,5.0]
)
data |> 
@vlplot() +
@vlplot(
    selection={
        brush={
            typ="interval",
            encodings=["x"]
        }
    },    
    mark="bar",
    encoding={
        x={field="date", typ="ordinal"},
        y={aggregate="mean", field="precipitation", typ="quantitative"},
        opacity={
            condition={selection="brush", value=1},
            value=0.7
        }
    }
) +
@vlplot(
    transform=[{
        filter={selection="brush"}
    }],
    mark="rule",
    encoding={
        y={aggregate="mean", field="precipitation", typ="quantitative"},
        color={value="firebrick"},
        size={value=3}
    }
)
```
The error message is:

> WARN Can not resolve event source: window

I am aware of this issue:
https://github.com/fredo-dedup/VegaLite.jl/issues/49
but don't understand everything.

Am I right that interactivity in a IJulia notebook is not yet possible with VegaLite.jl?

**Comment by davidanthoff** [comment]
The interactive features work in [JupyterLab](https://github.com/jupyterlab/jupyterlab) and [nteract](https://nteract.io/) in notebooks, but not in the classic Jupyter Notebook. Plots will show in the latter, but don't have the interactivity.
