### ISSUE TITLE
`@vlplot not defined` after install

### ISSUE THREAD

**Issue by jrising** [fredo-dedup/VegaLite.jl#110]
I've never used Vega-Lite before, but I tried it out in Julia 0.6.2:

```
julia> using VegaLite, VegaDatasets

julia> dataset("cars") |>
       @vlplot(
           :point,
           x=:Horsepower,
           y=:Miles_per_Gallon,
           color=:Origin,
           width=400,
           height=400
       )
ERROR: UndefVarError: @vlplot not defined
```

The install produced some warnings, including a possible problem with Node.js (but from the VegaLite building step, not from Node.js's process):
```
...
INFO: Cloning cache of NodeJS from https://github.com/davidanthoff/NodeJS.jl.git
INFO: Cloning cache of Rsvg from https://github.com/lobingera/Rsvg.jl.git
INFO: Cloning cache of VegaLite from https://github.com/fredo-dedup/VegaLite.jl.git
...
INFO: Installing NodeJS v0.4.0
INFO: Installing Rsvg v0.2.0
INFO: Installing VegaLite v0.1.0
...
INFO: Building NodeJS
INFO: Downloading Node.js binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.8M  100 10.8M    0     0  2682k      0  0:00:04  0:00:04 --:--:-- 2692k
INFO: Extracting Node.js binary
INFO: Building Rsvg
INFO: Building VegaLite
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN lifecycle npm is using /home/risingj/.julia/v0.6/NodeJS/deps/bin/node-v8.10.0-linux-x64/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> canvas@1.6.11 install /home/risingj/.julia/v0.6/VegaLite/deps/node_modules/canvas
> node-gyp rebuild

/usr/bin/env: ‘node’: No such file or directory

> canvas-prebuilt@1.6.0 install /home/risingj/.julia/v0.6/VegaLite/deps/node_modules/canvas-prebuilt
> node-pre-gyp install

/usr/bin/env: ‘node’: No such file or directory
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN vegalitejl@1.0.0 No description
npm WARN vegalitejl@1.0.0 No repository field.
npm WARN vegalitejl@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 (node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.0 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT
```

**Comment by oheil** [comment]
I had the same problem. After removing the the package directory ~/.julia/v0.6/VegaLite and running
```
Pkg.rm("VegaLite")
Pkg.add("VegaLite")
Pkg.update()
```
again it worked.
I didn't know what and why it happened, but maybe the above steps just help around the problem.

**Comment by davidanthoff** [comment]
It looks like it is installing VegaLite.jl v0.1.0 which is super old. We did have a really nasty problem with these old versions: their ``build.jl`` step was buggy, and it put the git repo for VegaLite.jl into a dirty state, effectively preventing any further updates of VegaLite.jl on your local system (because ``Pkg.update()`` doesn't touch repos that are dirty). That of course is really, really bad, but there is nothing we can do about that at this point...

The solution here is what @oheil recommended: just delete the whole ``~/.julia/v0.6/VegaLite`` folder, and then run a ``Pkg.update()`` (you don't have to do the ``Pkg.rm`` and ``Pkg.add`` step, just deleting the folder on disc should be enough).

**Comment by jrising** [comment]
You're right; I did this on a computer that I hadn't run `Pkg.update` on in a fair while.  I have another problem, but most of the examples work now.  Thank you!

**Comment by joyceraraujo** [comment]
I also tried to install VegaLite but I got the same problem.  I applied the steps above but unfortunately it didn't work.  Firstly, I deleted the whole folder **C:\JuliaPro-0.6.2.2\pkgs-0.6.2.2\v0.6\VegaLite** . Then I executed `Pkg.update()`, getting the following output:
```
 julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Installing VegaLite v0.2.0
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building Cairo
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building Rsvg
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building NodeJS
INFO: Building VegaLite
npm WARN vegalitejl@1.0.0 No description
npm WARN vegalitejl@1.0.0 No repository field.
npm WARN vegalitejl@1.0.0 No license field.

added 161 packages in 27.741s
```
Then I tried to `using VegaLite` and I got the following error ERROR: `LoadError: UndefVarError: @vlplot not defined`

Anyone has another idea how to solve it  ? Thanks in advance.

**Comment by davidanthoff** [comment]
Hm, this is strange, you are getting an old VegaLite.jl version, even though you do a ``Pkg.update()``... I do see that you are using JuliaPro? As far as I understand it, package management is quite broken on JuliaPro, so really the only suggestion I have is to try to install a "normal" julia and try it in that environment, or ask Julia Computing for support with JuliaPro...

**Comment by joyceraraujo** [comment]
I see. I'm indeed using JuliaPro(free version) and to install a "normal" julia it's a not an option for me because I have been working in a huge optimization problem and using Juno it's more friendly to model it. Thanks anyway.

**Comment by joyceraraujo** [comment]
AAA interesting!! Thanks for this tip :+1:  :+1:
