### ISSUE TITLE
Heatmap from a 2d Matrix

### ISSUE THREAD

**Issue by asbisen** [fredo-dedup/VegaLite.jl#115]
Is it possible to create a heatmap with `z` values. All the examples in the document seems to perform aggregation / binning in VegaLite. What if I have a matrix 

```julia
df = rand(1:100, (3,3)) |> DataFrame

│ Row │ x1 │ x2 │ x3 │
├─────┼────┼────┼────┤
│ 1   │ 72 │ 71 │ 46 │
│ 2   │ 67 │ 82 │ 17 │
│ 3   │ 98 │ 17 │ 61 │
```

How can I create a heatmap out of this dastaset?

**Comment by jtackm** [comment]
Converting to a tidy DataFrame first seems to work:

```julia
df = rand(1:100, (3,3)) |> DataFrame

tidy_df = copy(df)
tidy_df[:row] = 1:size(tidy_df, 1)
tidy_df = stack(tidy_df, names(tidy_df)[1:end-1])
```
![image](https://user-images.githubusercontent.com/16350312/43012599-d01129ba-8c46-11e8-8efc-a24ae176255d.png)

```julia
using VegaLite
tidy_df |> @vlplot(:rect, x="variable:n", y="row:n", color="value:q", width=300, height=300)
```
![image](https://user-images.githubusercontent.com/16350312/43012469-9036f234-8c46-11e8-9a43-64b4404a354c.png)
