### ISSUE TITLE
support of "application/vnd.vegalite.v2+json"

### ISSUE THREAD

**Issue by cnliao** [fredo-dedup/VegaLite.jl#127]
The latest Jupyterlab comes with vegalite included, so I imagine that this should work:
```
spec = raw"""
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
"""
struct A
    s::String
end
function Base.show(io::IO, m::MIME"application/vnd.vegalite.v2+json", x::A)
    print(io, x.s)
end
display("application/vnd.vegalite.v2+json", A(spec)) # or simply `A(spec)`
```
So vegalite can work in jupyterlab even without (the excellent) VegaLite.jl.
But currently the above code snippet gives a "Javascript Error: undefined" error.
Any thought on how to fix this?

**Comment by davidanthoff** [comment]
We support that MIME type by default (see [here](https://github.com/fredo-dedup/VegaLite.jl/blob/98cfcac676b81609f4db3c894c78ac982cbdd873/src/rendering/show.jl#L47)). So if you run in JupyterLab, we use exactly that mechanism to show specs.

We also support a ``vl`` string macro that allows you to type in specs directly, see [here](http://fredo-dedup.github.io/VegaLite.jl/latest/userguide/vlspec.html#The-vl-string-macro-1).

Let me know if you were thinking of anything else!

**Comment by cnliao** [comment]
Currently the following does not work. I think it's an issue with IJulia and will post a fix soon.
```
using VegaLite
spec = vl"""
{
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
"""
display("application/vnd.vegalite.v2+json", spec)
```

`display(spec)` already works, but IJulia will render and send *every* supported mime type in this case (a.k.a. additional png and svg). I want an interactive app to be more responsive so would like to avoid that overhead.

Another use case is to use already constructed vega(lite) json specs directly. The `@vl` macro is excellent at constructing such json strings.

**Comment by davidanthoff** [comment]
Yeah, that seems more on the IJulia side of things. Here we just implement the various ``show`` methods, and then it is really up to the client (IJulia) which ones to call.

If you have your spec as a string already, you can turn it into a vega-lite spec with ``VLSpec{:plot}(JSON.parse(content))``. We should probably make the easier, maybe by providing a constructor that just takes a ``String``, so that one doesn't have to worry about the JSON parsing... There will of course be a small overhead of turning things into a ``Dict`` etc tree again...

Btw., there is also full support for vega (not -lite) specs in this package, it is just all not exported and documented :)

**Comment by cnliao** [comment]
(Hopefully) fixed. Thank you very much!
