### ISSUE TITLE
Empty plot when using data keyword in @vlplot

### ISSUE THREAD

**Issue by leethargo** [fredo-dedup/VegaLite.jl#129]
I found an example ([gist](https://gist.github.com/leethargo/6a41060ae93abb6be786c191df7703bc)) which works as expected when I use the `data |> @vlplot` syntax, but fails when I use `@vlplot(..., data=data)` syntax.

According to the [docs](http://fredo-dedup.github.io/VegaLite.jl/stable/userguide/data.html#Using-inline-data-with-the-data-keyword-1), these two approaches should be equivalent, right?

My motivation for using the keyword `data` is that I want to layer two charts that each use different datasets, so I can't just pipe one table into the `@vlplot() + @vlplot` expression.

**Comment by leethargo** [comment]
I also found that I can not use `data |> @vlplot` where data is a simple `Array` of `NamedTuple`, but combining it with Query.jl operators works, as in `data |> @take(10) |> @vlplot`. Not sure if this is a bug or intentional, or just not implemented yet.

**Comment by leethargo** [comment]
I looked into the issue a little, and here is what I found so far:

In the case were `@vlplot` is called with the `data` keyword (given some tabular data), the function `fix_shortcuts` is handling the case [`if haskey(new_spec, "data")`](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/dsl_vlplot_macro/dsl_vlplot_macro.jl#L114) and in particular the subcase [`elseif TableTraits.isiterabletable(new_spec["data"])`](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/dsl_vlplot_macro/dsl_vlplot_macro.jl#L129) which does the transformation into an `Array` of `Dict`s.

But, when we call `@vlplot` without the `data` keyword, and instead call the resulting `VLSpec` with the `data` (or piping that in), [this function](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/vlspec.jl#L12) is called. Here, the same transformaton of the data to `Array` of `Dict` is [happening](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/vlspec.jl#L21), but, **in addtion**, the proper `type` is [set](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/vlspec.jl#L26) below `encoding`.

The latter piece of code produces the change from
```
Dict{String,Any} with 3 entries:
  "x"     => Dict{String,Any}("field"=>"date")
  "color" => Dict{String,Any}("field"=>"symbol")
  "y"     => Dict{String,Any}("field"=>"price")
```
to
```
Dict{String,Any} with 3 entries:
  "x"     => Dict{String,Any}("field"=>"date","type"=>"nominal")
  "color" => Dict{String,Any}("field"=>"symbol","type"=>"nominal")
  "y"     => Dict{String,Any}("field"=>"price","type"=>"quantitative")
```

I believe that this difference is responsible for the empty plot and will attempt to produce a patch to fix it.

**Comment by davidanthoff** [comment]
The Tables.jl bug is fixed on Tables.jl#master, we just need to wait for a new version to be tagged there, and then this should all work :)

**Comment by davidanthoff** [comment]
Here is the METADATA tag that we need to wait for now: https://github.com/JuliaLang/METADATA.jl/pull/19686
