### ISSUE TITLE
IJulia integration doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/VegaLite.jl#14]
Starting on Tue morning I can't get any plot to show in IJulia. When I e.g. execute the example from the README in an IJulia cell, I just get an empty output cell. This happens on 3 computers on Windows, and I'm 99% sure that at least on one of them things worked Mon night and that I haven't updated anything since on that machine.

Everything works great if I plot from the REPL.

I tested this on Chrome and Edge.

**Comment by davidanthoff** [comment]
@fredo-dedup And I just tried this on yet another system, an Ubuntu machine, and it also doesn't work there.

**Comment by fredo-dedup** [comment]
And I think that it doesn't work also from Juno since v0.0.2.
I will take a look as soon as I can...

**Comment by davidanthoff** [comment]
Yes, I also couldn't get it to run on Juno. Thanks!

**Comment by fredo-dedup** [comment]
Hopefully v0.0.3 should correct both. Current master now works for me.

**Comment by davidanthoff** [comment]
Yes, current master works for me on IJulia as well. I haven't tested the Juno work (not using that).

Thanks a lot!
