### ISSUE TITLE
Request: make tempname and launch_browser configurable

### ISSUE THREAD

**Issue by tkf** [fredo-dedup/VegaLite.jl#141]
It would be nice if users can configure what `tempname` and `launch_browser` are used.  My motivation is to use a static `tempname` and do-nothing `launch_browser` function so that I can open a single tab with `livereload` to keep previewing VegaLite.jl output without opening a new tab every time.

Here is a possible UI:

```julia
module VegaLite
...

mutable struct Configuration
    tempname
    launch_browser
end

const CONFIG = Configuration(tempname, launch_browser)

...
end
```

and usage:

```julia
using VegaLite
VegaLite.CONFIG.tempname = () -> "/tmp/vegalite-jl-ouptut"
VegaLite.CONFIG.launch_browser = let opened = false
    function(path)
        if !opened
            start livereload server and open a URL
            opened = true
        end
    end
end
```

Edit: Actually, I realized that the paths to JS libraries are using `file://` so my example won't work.

**Comment by davidanthoff** [comment]
Maybe that UI feature is something we could add to https://github.com/queryverse/ElectronDisplay.jl? Or do you actually like that things show up in a browser?

**Comment by tkf** [comment]
I didn't know about ElectronDisplay.jl.  Thanks a lot!  It'd be perfect for me if ElectronDisplay.jl can re-use the same Window.  Does it make sense to have such an option?

**Comment by davidanthoff** [comment]
Yeah, I think ElectronDisplay could for example reuse the window and have a back and forward button so that one can cycle through all plots that one has created. And maybe even a list view on the left with all the plots. It really is very bare bone right now.
