### ISSUE TITLE
Are tooltip hover labels not implemented in VegaLite.jl ?

### ISSUE THREAD

**Issue by gtollefson** [fredo-dedup/VegaLite.jl#142]
I would like to use VegaLite.jl to create a heatmap like the JS example found [here](https://vega.github.io/editor/#/)

Are [tooltips](https://vega.github.io/vega-lite/docs/tooltip.html) supported by VegaLite.jl?

We would like to use VegaLite.jl in our visualization tool development project but require a package that supports hover labels.

**Comment by davidanthoff** [comment]
Alright, I just fixed the bug with multiple tooltips. That can still be improved (https://github.com/fredo-dedup/VegaLite.jl/issues/145), but for now it should at least work.

Do let me know how things are working out for your project!
