### ISSUE TITLE
How to make a histogram

### ISSUE THREAD

**Issue by panlanfeng** [fredo-dedup/VegaLite.jl#3]
I was trying the following code
~~~
x  = randn(1000);
v = data_values(x=x) +    
             mark_bar() +   
             encoding_x_quant(value=:x, scale(bandSize=.5)) +
             encoding_y_quant(aggregate="count")
~~~
but I got error message:
"MethodError: `encoding_y_quant` has no method matching encoding_y_quant()"

Or what should be the right way to create a histogram?

**Comment by fredo-dedup** [comment]
Thanks or your interest and for filing this issue !

This should work (explanation follow) :

```julia
v = data_values(x=x) +    
    mark_bar() +   
    encoding_x_quant(:x, bin=true) +
    encoding_y_quant(:*, aggregate="count")
```

`encoding_...` functions need a first argument that is either a Symbol if you need to bind it to a `field` property or another type (String, numbers, ..) that is mapped to a `value` property. This first argument can then be followed by keyword arguments for other properties.

You should also indicate that you want binning for the x axis with `bin=true`.

Lastly, scale properties should be passed as `.., scale = scale(bandSize=.5),... `. That part of the syntax is a bit clumsy I admit !

**Comment by panlanfeng** [comment]
Thanks, It works!
Hope to see more documentation and examples in the future.
