### ISSUE TITLE
Encoding API

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/VegaLite.jl#35]
Here is an idea for a slightly tweaked encoding API: don't have a ``encoding`` function, instead have functions like ``encode_x``, ``encode_y``, ``encode_color`` etc. These would also replace the current ``xquantitative`` etc. functions. 

These new ``encode_x`` functions would take a positional first argument that could either be a ``Symbol`` (to reference a field), or a ``String`` that provides some convenient shortcut syntax.

So some of the examples would look like this:
````julia
mpg |> # add values ('data()' need the VegaLite qualification because it is exported by RDatasets too)
  markpoint() |>
  encode_x(:Cty, axis=nothing) |>
  encode_y(:Hwy, vlscale(zero=false)) |>
  encode_color(:Manufacturer) |>    # bind color to :Manufacturer, nominal scale
  config(vlcell(width=350, height=400))
````
What we lose with that is the mandatory decision whether one wants to encode a field as quant, nominal etc. But I think that is good, in most cases we should be able to just use the julia data type to decide a sensible default for that.

The other thing we lose is the ``encoding`` function that groups all the encodings. But does that provide any benefit? I kind of feel that one might as well just add individual encodings directly into the spec, and it should be clear that they must go into the ``encodings`` JSON section, where else could they go? So it seems to me that getting rid of that one level in the hierarchy in the julia API would also just simplify things for users.

I would also suggest a abbreviated string syntax for this like altair, maybe even just use exactly the same syntax. For example, ``encode_x("Cty:Q")`` would mean that ``Cty`` should be used as a quant field. ``encode_x("Cty:N")`` would mean it should be used as a nominal field etc.

**Comment by davidanthoff** [comment]
First cut in #45. That will also add the Altair shorthand option.

**Comment by fredo-dedup** [comment]
This looks like a good idea. :+1:
