### ISSUE TITLE
Fix doc page

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/VegaLite.jl#39]
Hi @fredo-dedup I think the doc build is now working and properly pushing things to the gh-pages branch, but the URL still doesn't seem to work.

Could you double check that in the settings for this github repo, on the first page, under ``GitHub Pages`` you have selected ``gh-pages branch`` for ``Source``? That is the setting we need, everything else won't work.

**Comment by fredo-dedup** [comment]
I changed it to gh-pages and it now works (latest only). 

I tried to make those docs appear for a long time but didn't know about this setting, didn't see it in the Documenter tutorial.

**Comment by davidanthoff** [comment]
Was there a reason to go back to the mkdocs option? At least locally I had the impression that the docs seemed to build just fine with the built-in html option in Documenter?
