### ISSUE TITLE
IJulia story

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/VegaLite.jl#49]
I've spent a fair bit of time now thinking through the best way to support IJulia. Essentially I think we might want to not have a ``show`` method for the html MIME type because I think no matter what we do, we'll run into trouble.

Here are the three options I see that one can use in the generated HTML:
1. Embed all the vega and vega-lite javascript in the HTML. We would probably use something like browserify for that. That is the strategy that plotlyjs.jl uses in some cases. I think at the end of the day this is unrealistic because it just really bloats IJulia notebooks like crazy.
2. Emit HTML that loads vega-lite from some URL. That is what we do today. Main issue is that it doesn't work when one is offline.
3. Emit HTML that uses a local copy of the vega-lite javascript. Main issue is that it doesn't work if one gives the file to someone else.

I think at the end of the day all of these options have such significant drawbacks that we should just cut the HTML ``show`` method entirely.

At that point we would have the following situation:
- Jupyterlab and nteract will use the native vega-lite MIME type. This is the ideal situation in any case, we just embed the vega-lite spec itself, and both of those clients handle all the vega-lite deployment for us. I have that scenario almost working, just waiting for one more merge over at IJulia. nteract already ships with vega-lite support out of the box, and juptyerlab right now has an extension for that, but they plan to move that into the normal jupyterlab deployment.
- On the classical notebook (which will be phased out as jupyterlab gets more mature) we don't have that option. I would suggest we just rely on PNG or SVG for that case. Yes, we lose the interactivity, but on the flipside things will work without tech hiccups. And if folks do want interactivity, they can just move over to jupyterlab, which they have to do in any case soonish.

@fredo-dedup what do you think about that?

**Comment by fredo-dedup** [comment]
I didn't know that Jupyterlab would be getting a native VegaLite spec interpreter, this will greatly simplify things.
Do you think it would be possible to have a user setting allowing the fallback to SVG/PNG in case the user has the classical notebook ? Or even better if it can be detected from within julia ?
Otherwise, I fully agree with your plan.

**Comment by davidanthoff** [comment]
Well, if we have show methods for png, svg and the vega-lite spec, then all three representations are embedded in the Jupyter notebook, and whatever client a user has will pick the version that works, so I think we don't even need a fallback, the fallback is essentially there already.

I'll prep a PR that just removes the html ``show`` method.

**Comment by davidanthoff** [comment]
@randyzwitch This might be of interest for Vega.jl as well. jupyterlab and nteract natively support (or will support soon) vega and vega-lite mime types, so on those platforms this whole HTML mess is unnecessary, one can just ship the spec itself to the notebook and then the clients handle the rest.

So far I've added support for the vega-lite MIME type to IJulia, but now that I know what needs to be done it would be super easy for me to do a PR that also adds the vega MIME type. At that point you would just have to add a show method for that MIME type to Vega.jl, it would be super simple (the one for VegaLite.jl is this [one liner](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/show.jl#L15)).
