### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/VegaLite.jl#63]
Trying to convert a spec to SVG when it has a URL as the data source throws the following error:
````
julia> savefig("foo.svg", f)
WARN Invalid field type "undefined" for channel "x", using "quantitative" instead.
WARN Invalid field type "undefined" for channel "size", using "quantitative" instead.
WARN Invalid field type "undefined" for channel "y", using "quantitative" instead.
ERROR Loading failed https://raw.githubusercontent.com/vega/new-editor/master/data/movies.json ReferenceError: XMLHttpRequest is not defined
    at request$1 (C:\Users\david\.julia\v0.6\VegaLite\deps\node_modules\vega\build\vega.js:1594:13)
    at C:\Users\david\.julia\v0.6\VegaLite\deps\node_modules\vega\build\vega.js:1995:15
    at new Promise (<anonymous>)
    at Object.http (C:\Users\david\.julia\v0.6\VegaLite\deps\node_modules\vega\build\vega.js:1994:10)
    at C:\Users\david\.julia\v0.6\VegaLite\deps\node_modules\vega\build\vega.js:1922:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
````

@domoritz, do you have some idea what the root cause of this might be? The general story here is that we run [this](https://github.com/fredo-dedup/VegaLite.jl/blob/34214d3fdcf005824415dac87e71a8c0c70ffd50/src/compilesvg.js) script to convert the vega-lite spec to SVG. In the build phase of the package we download vega and vega-lite via npm with [this](https://github.com/fredo-dedup/VegaLite.jl/blob/34214d3fdcf005824415dac87e71a8c0c70ffd50/deps/package.json) package file.

I completely understand that digging into the details of this package is probably unrealistic for you, but I guess there is a small chance that you might have seen a similar error before and might just know what we should do :) Thanks!

**Comment by domoritz** [comment]
Hmm, I have not seen that error before. Are you familiar with the vg2svg and vl2svg scripts in Vega and Vega-Lite?

**Comment by davidanthoff** [comment]
I think the update to vega 4.0.0 solved this, it seems to no longer use XMLHttpRequest, and with the new version this error doesn't show up anymore.

I've adopted the code from the two scripts you mentioned and use something similar ([here](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/rendering/compilesvg.js) and [here](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/rendering/compilevg2svg.js)) to do conversions in this package here.

**Comment by domoritz** [comment]
Vega 4 switched to using fetch, which is the main reason that we needed a new major version.
