### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by davidanthoff** [fredo-dedup/VegaLite.jl#9]
I just found this package, and it seems fantastic! This actually seems the best option on julia right now for people that are looking for a grammar of graphics API. Really surprised this package is not getting much, much more publicity...

In any case, could you tag a new version? The latest tagged versions has lots of deprecation warnings on julia 0.5, would be great to have a tagged version that doesn't have these. I just tried the ``devl`` branch, and all those seem to be fixed there.

**Comment by davidanthoff** [comment]
@fredo-dedup Bump, any chance you could tag a version? I would like to showcase the package in my class, and it would be much simpler if there was a tagged version. Thanks.

**Comment by fredo-dedup** [comment]
@davidanthoff : just tagged a new version that should remove deprecation warnings and correct a display bug (graphs showing twice in the browser).

Thank you for your interest ! I would be glad to hear feedback from you or your class if any.
